config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'welcome#index'

    get '/dashboard' => 'dashboard#index'

    resource :hosts
    resources :tables
    resource :users
    resource :sessions, only: %i(new create destroy)

    post 'tables/:table_id' => 'tables#reservation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    validates :address, presence: true
    validates :phone, presence: true
    validates :email, uniqueness: true, presence: true
    validates :password, length: { minimum: 6 }

    has_many :tables
end

app/models/table.rb
class Table < ApplicationRecord
    validates :table_name, :table_date, :table_time, :number_of_seats, presence: true
    validates :number_of_seats, numericality: { greater_than: 0}

    belongs_to :host
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6 }

    has_and_belongs_to_many :tables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    helper_method :current_user
    helper_method :current_host

    private

    def current_user
        session[:user_id] && User.find(session[:user_id])
    end

    def current_host
       session[:host_id] && Host.find(session[:host_id])
    end

    def require_login
        unless current_user || current_host
            flash[:danger] = "Please log in or register"
            redirect_to new_users_path
        end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :require_login

    def index
        if current_user
            @main = User.find(current_user).tables
        elsif current_host
            @main = Table.where(host_id: current_host.id)
        end
    end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

    def show
       @host = current_host
    end

    def new
        @host = Host.new
    end

    def create
        @host = Host.new(host_params)

        if @host.save
            flash[:success] = "Welcome to GameTable, #{@host.name}!"
            session[:host_id] = @host.id
            redirect_to dashboard_path
        else
            flash[:danger] = "We're sorry, but something went wrong."
            render :new
        end
    end

    def edit
       @host = current_host
    end

    def update
        @host = current_host

        if @host.update_attributes(host_params)
            flash[:success] = "Your information has been updated"
            redirect_to root_path
        else
            flash[:danger] = "Sorry, something went wrong"
            render :edit
        end
    end

    private

    def host_params
        params.require(:host).permit(:name, :address, :phone, :email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
        if current_user || current_host
            flash[:notice] = "You're already logged in"
            redirect_to root_path
        end
  end

    def create
        if User.find_by email: session_params[:email]
            user = User.find_by email: session_params[:email]

            if user.authenticate(session_params[:password])
                flash[:success] = "Successfuly logged in as #{user.first_name} #{}!"
                session[:user_id] = user.id
                redirect_to dashboard_path
            else
                flash[:danger] = "Invalid credentials"
                render :new
            end

        elsif Host.find_by email: session_params[:email]
            host = Host.find_by email: session_params[:email]

            if host.authenticate(session_params[:password])
                flash[:success] = "Successfuly logged in as #{host.name}!"
                session[:host_id] = host.id
                redirect_to dashboard_path
            else
                flash[:danger] = "Invalid credentials"
                render :new
            end
        end
    end

  def destroy
        if session[:user_id]
            session.delete(:user_id)
            flash[:success] = "Logged out successfully"
            redirect_to root_path
        elsif
            session.delete(:host_id)
            flash[:danger] = "Logged out successfully"
            redirect_to root_path
        end
  end

    private

    def session_params
       params.require(:session).permit(:email, :password)
    end

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

    def index
       @tables = Table.all
    end

    def new
       @table = Table.new
    end

    def create
        @table = Table.new(table_params)
        @table.host_id = current_host.id

        if @table.save
            flash[:success] = "Your table has been created!"
            redirect_to dashboard_path
        else
            flash[:danger] = "Sorry, something went wrong"
            render :new
        end
    end

    def reservation
        @table = Table.find(params[:table_id])

        if @table.users << current_user
            flash[:success] = "You have been registered"
            redirect_to dashboard_path
        else
            flash[:danger] = "Sorry, something went wrong. Please try again."
            redirect_to action: "index"
        end
    end

    private

    def table_params
        params.require(:table).permit(:table_name, :table_date, :table_time, :number_of_seats)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        if current_user()
            flash[:success] = "You're already logged in"
            redirect_to root_path
        else
            @user = User.new
        end
    end

    def show
       @user = current_user
    end

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:success] = "Successfully signed up!"
            session[:user_id] = @user.id
            redirect_to dashboard_path
        else
            flash[:danger] = "Please try again. Something went wrong."
            render :new
        end
    end

    def edit
        @user = current_user
    end

    def update

        @user = current_user

        if @user.update_attributes(user_params)
            flash[:success] = "Your information has been updated"
            redirect_to root_path
        else
            flash[:danger] = "Sorry, something went wrong"
            render :edit
        end
    end

    private

    def user_params
       params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<% if current_user %>
    <h2>Registered Events</h2>
    <% @main.each do |reservation| %>
        <div>
            <h3><%= reservation.table_name %></h3>
            <h4><%= reservation.table_date.to_formatted_s(:long)%></h4>
            <h4><%= reservation.table_time.strftime("Starts at %I:%M%p")%></h4>
        </div>
    <% end %>
    <%= link_to "View available tables", tables_path %>
<% elsif current_host %>
    <h2>Current Tables</h2>
    <% @main.each do |table| %>
        <div>
            <h3><%= table.table_name %></h3>
            <h4><%= table.table_date.to_formatted_s(:long)%></h4>
            <h4><%= table.table_time.strftime("Starts at %I:%M%p")%></h4>
        </div>
    <% end %>
    <%= link_to "Create a new table", new_table_path %>
<% end %>

app/views/hosts/edit.html.erb
<h1>Edit Information for <%= @host.name %></h1>

<% if @host.errors.any? %>
    <% @host.errors.full_messages.each do |message|%>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @host, url: hosts_path,  html: {method: "patch"} do |u| %>
    <div class="form-group">
        <%= u.label :name %>
        <%= u.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :address %>
        <%= u.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :phone %>
        <%= u.telephone_field :phone, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :email %>
        <%= u.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password %>
        <%= u.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="submit">
        <%= u.submit "Update Information", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/hosts/new.html.erb
<h1>Register your buisness!</h1>

<% if @host.errors.any? %>
    <% @host.errors.full_messages.each do |message|%>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @host do |u| %>
    <div class="form-group">
        <%= u.label :name %>
        <%= u.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :address %>
        <%= u.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :phone %>
        <%= u.telephone_field :phone, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :email %>
        <%= u.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password %>
        <%= u.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="submit">
        <%= u.submit "Register" %>
    </div>
<% end %>

app/views/hosts/show.html.erb
<h1>Account Information</h1>

<h3>Name: <%= @host.name %></h3>

<h3>Address: <%= @host.address %></h3>

<h3>Phone: <%= @host.phone %></h3>

<h3>Email: <%= @host.email %></h3>

<h4><%= link_to "Edit Information", edit_hosts_path %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Gametable</title>
        <%= csrf_meta_tags %>

        <!--Bootstrap CDN-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/"><%= image_tag 'GameTable.svg', alt: 'Welcome to GameTable' %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav navbar-left">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/dashboard">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/hosts/new">Register as a Host</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    <% if current_user %>
                    <li class="nav-item">
                        <%= link_to "Account: #{current_user.first_name} #{current_user.last_name}", users_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log Out", sessions_path, method: :delete, class: "nav-link"%>
                    </li>
                    <% elsif current_host %>
                    <li class="nav-item">
                        <%= link_to "Account: #{current_host.name}", hosts_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log Out", sessions_path, method: :delete, class: "nav-link" %>
                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_users_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log In", new_sessions_path, class: "nav-link" %>
                    </li>
                    <% end %>
                </ul>
            </div>
        </nav>

        <% if flash.any? %>
            <% flash.each do |key, value| %>
                <p class="alert alert-<%= key %>"><%= value %></p>
            <% end %>
        <% end %>

        <%= yield %>
     </body>
</html>

app/views/tables/index.html.erb
<h1>Available Tables</h1>

<% @tables.each do |table| %>
    <h2><%= table.table_name %></h2>
    <h3>Hosted by: <%= Host.find(table.host_id).name %></h3>
    <h4>Date: <%= table.table_date.to_formatted_s(:long)%></h4>
    <h4>Time: <%= table.table_time.strftime("Starts at %I:%M%p")%></h4>
    <%= link_to "Reserve your seat", "tables/#{table.id}", method: 'post'%>
<% end %>

app/views/tables/new.html.erb
<h1>Create a new table</h1>

<% if @table.errors.any? %>
    <% @table.errors.full_messages.each do |message|%>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @table do |t| %>
    <div class="form-group">
        <%= t.label :table_name %>
        <%= t.text_field :table_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= t.label :table_date %>
        <%= t.date_field :table_date, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= t.label :table_time %>
        <%= t.time_field :table_time, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= t.label :number_of_seats%>
        <%= t.number_field :number_of_seats, class: "form-control" %>
    </div>
    <div class="submit">
        <%= t.submit "Create Table", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Information for <%= @user.first_name %> <%= @user.last_name %> </h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message|%>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @user, url: users_path,  html: {method: "patch"} do |u| %>
    <div class="form-group">
        <%= u.label :first_name %>
        <%= u.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :last_name %>
        <%= u.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :email %>
        <%= u.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password %>
        <%= u.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="submit">
        <%= u.submit "Update Information", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Now!</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message|%>
        <p><%= message %></p>
    <% end %>
<% end %>

<%= form_for @user do |u| %>
    <div class="form-group">
        <%= u.label :first_name %>
        <%= u.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :last_name %>
        <%= u.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :email %>
        <%= u.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password %>
        <%= u.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= u.label :password_confirmation %>
        <%= u.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="field submit">
        <%= u.submit "Sign Up", class: "btn btn-primary" %>
    </div>
<% end %>
<hr>
<h3>Already a member? <%= link_to "Log In Now", new_sessions_path, class: "text-primary" %></h3>

app/views/users/show.html.erb
<h1>Account Information</h1>

<h3>Name: <%= @user.first_name %> <%= @user.last_name %> </h3>

<h3>Email: <%= @user.email %></h3>

<h4><%= link_to "Edit Information", edit_users_path %></h4>

app/views/welcome/index.html.erb
<h1>Welcome to Gametable!</h1>

<%= image_tag 'GameTable.svg', alt: 'Welcome to GameTable' %>